
# 项目短口号
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    name:  test
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  # redis配置

    redis:
  #  数据库索引
      database: 0
  #    服务器地址
      host: 127.0.0.1
  #    服务器连接端口
      port: 6379
  #    链接密码
      password:
  #    链接池
      pool:
  #    最大连接数（负值表示没有限制）
        max-active: 8
  #      最大阻塞等待时间（负值表示没有限制）
        max-wait: 1
  #      最大空闲链接
        max-idle: 8
  #      最小空闲链接
        min-idle: 0
  #    链接超时时间（毫秒）
      timeout: 0




# 配置mybatis
mybatis:
  config-location: classpath:config/mybais_config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qishun.qishunstudy.model

mapper:
  mappers:  com.qishun.qishunstudy.dao
  not-empty: false
  identity: MYSQL

# pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
















